
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMMA IDENTIFIER OPexpressions : expression\n                   | expression AND expressionsexpression : IDENTIFIER op identifiersidentifiers : IDENTIFIER\n                   | IDENTIFIER COMMA identifiersop : OP'
    
_lr_action_items = {'IDENTIFIER':([0,4,5,6,10,],[3,3,8,-6,8,]),'$end':([1,2,7,8,9,11,],[0,-1,-2,-4,-3,-5,]),'AND':([2,8,9,11,],[4,-4,-3,-5,]),'OP':([3,],[6,]),'COMMA':([8,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressions':([0,4,],[1,7,]),'expression':([0,4,],[2,2,]),'op':([3,],[5,]),'identifiers':([5,10,],[9,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expressions","S'",1,None,None,None),
  ('expressions -> expression','expressions',1,'p_expressions','parser.py',8),
  ('expressions -> expression AND expressions','expressions',3,'p_expressions','parser.py',9),
  ('expression -> IDENTIFIER op identifiers','expression',3,'p_expression','parser.py',22),
  ('identifiers -> IDENTIFIER','identifiers',1,'p_identifiers','parser.py',27),
  ('identifiers -> IDENTIFIER COMMA identifiers','identifiers',3,'p_identifiers','parser.py',28),
  ('op -> OP','op',1,'p_op','parser.py',42),
]
